//===- QnnToQisa.h - QNN -> Q-ISA lowering pass -----------------*- C++ -*-===//
//
// Mechanism proof: lowers the linear-chain qnn ops (qnn.matmul -> qisa.gemm/
// gemv, qnn.rmsnorm -> qisa.rmsnorm) plus the surrounding mode/config/dma/
// barrier scaffolding. The full-model GEMM/GEMV sequence is generated by the
// Python lowering (qforge/lowering.py); this pass demonstrates the same
// lowering mechanism inside MLIR.
//
//===----------------------------------------------------------------------===//

#ifndef QNN_QNNTOQISA_H
#define QNN_QNNTOQISA_H

#include "mlir/IR/BuiltinOps.h"
#include "mlir/Pass/Pass.h"

namespace mlir {
namespace qnn {
std::unique_ptr<Pass> createQnnToQisaPass();

void registerQnnPasses();

} // namespace qnn
} // namespace mlir

#endif // QNN_QNNTOQISA_H
